name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # pick the Node version to use and install it
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: bahmutov/npm-install@v1
    - name: Generate package-lock.json (if needed)
      run: npm install
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Generate package-lock.json (if needed)
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
