name: Push Events
on:
  push:
    branches: -main
      -test1
      -test2
      -test9
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push event on all the branches"
