name: Manual Test Workflow
on:
  workflow_call:

jobs:
  run-manual-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Info
        run: |
          echo "Running manual test tasks"
          echo "Current time is $(date)"
